### ISSUE TITLE
There was a problem running this project

### ISSUE THREAD

**Issue by zjavax** [Ausstaker/cardano-walletconnector-demo#1]
I'm going to run this, and I get an error：

blockfrost.cardano.mainnet.project.id=<insert output of EncryptionUtil.encrypt("testnetxf0Kv0lwHjAbQxLmd55h5vDc*********")>

2022-03-13 13:31:22.167 [ERROR] [main] [au.com.ausstaker.cardano_dappconn_test.config.EncryptedPropertyConfigurer:30] Error while decoding the value[<insert output of EncryptionUtil.encrypt("testnetxf0Kv0lwHjAbQxLmd55h5vDc*******")>]
org.jasypt.exceptions.EncryptionOperationNotPossibleException: null
	at org.jasypt.encryption.pbe.StandardPBEByteEncryptor.decrypt(StandardPBEByteEncryptor.java:1055)
	at org.jasypt.encryption.pbe.StandardPBEStringEncryptor.decrypt(StandardPBEStringEncryptor.java:725)
	at org.jasypt.encryption.pbe.PooledPBEStringEncryptor.decrypt(PooledPBEStringEncryptor.java:498)
	at au.com.ausstaker.cardano_dappconn_test.util.EncryptionUtil.decrypt(EncryptionUtil.java:23)
	at au.com.ausstaker.cardano_dappconn_test.config.EncryptedPropertyConfigurer.convertProperties(EncryptedPropertyConfigurer.java:28)
	at org.springframework.beans.factory.config.PropertyResourceConfigurer.postProcessBeanFactory(PropertyResourceConfigurer.java:83)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:284)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:166)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:678)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:520)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:760)
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174)
	at au.com.ausstaker.cardano_dappconn_test.Application.main(Application.java:15)
2022-03-13 13:31:22.168 [DEBUG] [main] [au.com.ausstaker.cardano_dappconn_test.config.EncryptedPropertyConfigurer:33] Setting property: blockfrost.cardano.mainnet.project.id
2022-03-13 13:31:22.169 [ERROR] [main] [org.springframework.boot.SpringApplication:821] Application startup failed

**Comment by tdedgx** [comment]
Hi, this just required encryption of your actual blockfrost api key using the test class - as discussed offline. Also, have updated this project to integrate latest cardano-serialisation-lib, eternl wallet connector and by default to use defaults for protocol params when on testnet rather than fetching from blockfrost, thus the blockfrost key itself is not required in this case
